apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: magento
  name: magento
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: magento
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: magento
    spec:
      containers:
      - env:
        - name: APACHE_LOG_LEVEL
          value: {{ .Values.apache.logLevel }}
        - name: ENABLE_SAMPLE_DATA
          value: {{ .Values.magento.sampleData }}
        - name: MAGENTO_ADMINURI
          value: {{ .Values.magento.adminURI }}
        - name: MAGENTO_DATABASE_NAME
          value: {{ .Values.magento.databaseName }}
        - name: MAGENTO_DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: password
        - name: MAGENTO_DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: user
        - name: MAGENTO_HOST
          value: {{ .Values.magento.host }}
        - name: MARIADB_HOST
          value: {{ .Values.mariadb.host }}
        - name: MARIADB_PORT_NUMBER
          value: {{ .Values.mariadb.port }}
        image: jamesbrink/magento:2.2-sd
        imagePullPolicy: ""
        name: magento
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
